// A trivial chat server.

caterwaul.clone('std seq montenegro')(function () {
  caterwaul.montenegro.server(8080) /se[
    // Server code:
    _.rpc('/chat/listen', fn_[clients.push(this)]).rpc('/chat/send', fn[message][seq[clients *![_(message)]], clients = seq[~[]], this('OK')]), where[clients = seq[~[]]],

    // Client code:
    _.html('/', qs[caterwaul.montenegro.rpc('/chat/listen')(fn[message][$('.log').append(html[div.message(message)]), this()]),
                   let*[send = caterwaul.montenegro.rpc('/chat/send')] in
                   $('body').append(html[div.log(input /enter(fn_[send($(this).val()), $(this).val('')]))])])]})();

// Generated by SDoc 
