// Various markup macros

caterwaul.clone('std montenegro')(function () {
  caterwaul.montenegro.server(8080) /se[_.html('/buttons', qs[$('body').append(html[div > [button('first'), button('second')]])])]})();

// Generated by SDoc 
