// Proxy test app

caterwaul.clone('std seq continuation montenegro')(function () {
  caterwaul.montenegro.server(8080) /se[
    _.proxy('/proxy/'),
    _.html('/', qs[$('body').append(html[input /val('www.google.com'), button('GET') /click(fn_[$.get('/proxy/#{$("input").val()}', fn[data][$('body').append(html[pre(data)])])])])])]})();

// Generated by SDoc 
