// HTTP redirect testing

caterwaul.clone('std montenegro')(function () {
  caterwaul.montenegro.server(8080) /se[
    _.redirect('/foo', 'http://www.google.com').
      redirect('/bar', 'http://www.yahoo.com', {code: 302}).
      redirect('/bif', 'http://www.ubuntu.com', {method: 'POST'}).
      redirect('/baz', 'about:blank', {code: 302, method: 'POST'})]})();

// Generated by SDoc 
