// Trivial RPC service.

caterwaul.clone('std montenegro')(function () {
  caterwaul.montenegro.server(8080) /se[_.rpc('/add-things', 'Adds two numbers and returns the result', fn[x, y][this(x + y)])];
})();

// Generated by SDoc 
