// Trivial reply service.

caterwaul.clone('std montenegro')(function () {
  caterwaul.montenegro.server(8080) /se[_.on('/hello', 'GET', fn[req, res][res /se[_.writeHead(200), _.end('Hi there')]])];
})();

// Generated by SDoc 
